version: '3.9'

services:
  development:
    image: tianon/true
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      selenium:
        condition: service_started

  postgres:
    image: postgres:10.15
    container_name: qna_postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ../log:/root/log:cached
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:4.0.9
    container_name: qna_redis
    volumes:
      - redis:/data
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  selenium:
    image: selenium/standalone-chrome:3.141.59-20201119
    container_name: qna_chrome
    ports:
      - 4444:4444

volumes:
  postgres:
    name: qna_volume_postgres
  redis:
    name: qna_volume_redis
