default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  username: <%= ENV.fetch('DB_USER', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', '1q2w3e4r') %>

development:
  <<: *default
  database: qna_development

test:
  <<: *default
  database: qna_test

production:
  <<: *default
  database: qna_production
  username: postgres
  password: <%= Rails.application.credentials[:production][:DB_PASSWORD] %>
